require("core.options")
require("core.keymaps")
require("plugins.plugins-setup")

-- 插件
require("plugins/nvim-tree")
require("plugins/lualine")
require("plugins/bufferline")
require("plugins/comment")
require("plugins/treesitter")
require("plugins/autopairs")
require("plugins/telescope")
require("plugins/toggleterm")
require("plugins/dashboard")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/gitsigns")
require("plugins/lspsaga")
-- require("plugins/which-key")
require("plugins/dap")
require("plugins/dapui")
require("plugins/dapvtext")
require("plugins/code-runner")
